# Generated by Django 5.1 on 2026-02-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarees_user', '0002_aboutstore_faq_saree_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
